version: '3.8'

services:
  ffc-pay-alert-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --loose"
    volumes:
      - azurite_data:/data
    ports:
      - "10021:10000"
      - "10022:10001"

volumes:
  azurite_data:
